config/routes.rb
Tabby::Application.routes.draw do

  resources :conversations

  resources :blood_pressures

  resources :photos

  resources :galleries

  resources :symptoms
  resources :doctor_visits
  resources :immunizations
  resources :conversations
  resources :messages
  resources :treatments
  resources :pharmacies
  resources :notifications
  resources :droplets
  resources :permissions
  resources :ko_medication_reviews
  resources :appointments
  resources :symptoms
  resources :ko_medications

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end

  get "profiles/show"

  resources :catalogs
  resources :statuses
  resources :documents
  resources :trackers
  resources :pages
  resources :goal_posts
  resources :medications
  resources :handshakes
  resources :conditions do
    resources :posts
    get 'privacy'
    resources :trackers
  end
  resources :episodes do
    resources :posts
  end
  resources :weights
  resources :heights
  resources :allergies
  resources :goal_posts
  resources :pictures
  resources :goals do
    resources :goal_posts
    get 'mark_complete'
  end

  resources :users do
    resources :handshakes
    resources :notifications
    resources :immunizations
    resources :symptoms
    resources :permissions
    resources :doctor_visits
    resources :conversations do
      resources :messages
    end
    resources :trackers do
      resources :datapoints
    end
    get 'mark_read'
    get 'apps'
    get 'network'
    get 'ecard'
    get 'network_feed'
    get 'network_permissions'
    get 'printable'
    get 'dashboard'
    get 'metrics'
    get 'summary'
    resources :pictures
    resources :albums do
      resources :pictures
    end
    resources :allergies
    resources :statuses
    resources :goal_posts
    resources :fitnesses
    resources :goals do
      resources :goal_posts
    end
    resources :conditions
    resources :episodes do
      resources :posts
    end
    resources :heights
    resources :weights
    resources :medications
  end
  resources :albums do
    resources :pictures
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :pictures
  resources :posts
  resources :datapoints

  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get 'static_pages/ecard'
  get 'static_pages/features'
  get "static_pages/company"
  get "static_pages/community_stats"
  get "static_pages/search"
  get "static_pages/roadmap"

  get "albums/form" => 'albums#form', as: :form

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user
  has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @conversations = current_user.conversations
  end

  def show
    @conversation = Conversation.find(params[:id])
    @user = @conversation.user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conversation }
    end
  end

  def update
    @conversation = Conversation.find(params[:id])
    @conversation.update(conversation_params)

    respond_to do |format|
      format.html { redirect_to user_summary_path(current_user), notice: 'Successfully updated!' }
      format.json { head :no_content }
    end
  end

  def new
    @user = User.find(params[:user_id])
    @conversation = @user.conversations.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conversation }
    end
  end
  
  def edit
    @conversation = Conversation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conversation }
    end
  end
  
  def destroy
    @conversation = Conversation.find(params[:id])
    @user = @conversation.user
    @conversation.destroy
    redirect_to user_summary_path(@conversation.user), :notice => "Successfully destroyed conversation."
  end

  def create
    @conversation = current_user.conversations.new( conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to user_summary_path(@conversation.user), notice: 'Conversation was successfully created.' }
        format.json { render json: @conversation, status: :created, location: @conversation }
      else
        format.html { render action: "new" }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:user_id, :other_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= simple_form_for(@conversation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :other_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<%= render 'layouts/panel_head' %>
<h2>
  <h1><%= fa_icon "envelope-o" %> Messages</h1>
</h2>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.user_id %></td>
        <td><%= conversation.other_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @conversation.user_id %>
</p>

<p>
  <strong>Other:</strong>
  <%= @conversation.other_id %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>