config/routes.rb
Tabby::Application.routes.draw do

  resources :conversations

  resources :blood_pressures

  resources :photos

  resources :galleries

  resources :symptoms
  resources :doctor_visits
  resources :immunizations
  resources :conversations
  resources :messages
  resources :treatments
  resources :pharmacies
  resources :notifications
  resources :droplets
  resources :permissions
  resources :ko_medication_reviews
  resources :appointments
  resources :symptoms
  resources :ko_medications

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end

  get "profiles/show"

  resources :catalogs
  resources :statuses
  resources :documents
  resources :trackers
  resources :pages
  resources :goal_posts
  resources :medications
  resources :handshakes
  resources :conditions do
    resources :posts
    get 'privacy'
    resources :trackers
  end
  resources :episodes do
    resources :posts
  end
  resources :weights
  resources :heights
  resources :allergies
  resources :goal_posts
  resources :pictures
  resources :goals do
    resources :goal_posts
    get 'mark_complete'
  end

  resources :users do
    resources :handshakes
    resources :notifications
    resources :immunizations
    resources :symptoms
    resources :permissions
    resources :doctor_visits
    resources :conversations do
      resources :messages
    end
    resources :trackers do
      resources :datapoints
    end
    get 'mark_read'
    get 'apps'
    get 'network'
    get 'ecard'
    get 'network_feed'
    get 'network_permissions'
    get 'printable'
    get 'dashboard'
    get 'metrics'
    get 'summary'
    resources :pictures
    resources :albums do
      resources :pictures
    end
    resources :allergies
    resources :statuses
    resources :goal_posts
    resources :fitnesses
    resources :goals do
      resources :goal_posts
    end
    resources :conditions
    resources :episodes do
      resources :posts
    end
    resources :heights
    resources :weights
    resources :medications
  end
  resources :albums do
    resources :pictures
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :pictures
  resources :posts
  resources :datapoints

  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get 'static_pages/ecard'
  get 'static_pages/features'
  get "static_pages/company"
  get "static_pages/community_stats"
  get "static_pages/search"
  get "static_pages/roadmap"

  get "albums/form" => 'albums#form', as: :form

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  
  def mark_as_read
    update_attribute(:b_read, true)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @notification = current_user.notifications.new
    @notifications = @user.notifications.order('created_at DESC')
  end

  def show
    @notification = Notification.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  def edit
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  def new
    @notification = current_user.notifications.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @user = @notification.user
    @notification.destroy
    redirect_to user_notifications_path(@notification.user), flash: { info: "Successfully destroyed notification."}
  end

  def create
    @notification = current_user.notifications.new( notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to user_notifications_path(@notification.user), notice: 'notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def notification_params
    params.require(:notification).permit(:user_id, :b_read, :content, :imageurl, :notificationurl)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :b_read %>
    <%= f.input :content %>
    <%= f.input :imageurl %>
    <%= f.input :notificationurl %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<%= render 'layouts/panel_head' %>
<h2>
  <h1><%= fa_icon "inbox" %> Notifications</h1>
</h2>
<% if !@notifications.any?{|immunization| immunization.b_read == true} %>
<p>
  <%= link_to user_mark_read_path(current_user), class: ' btn-' do %>
  <%= fa_icon "check" %>  Mark All As Read
  <% end %>
</p>
<% end %>
<table class='table table-striped table-hover table-responsive'>

  <tbody>
    <% @notifications.each do |notification| %>
    <% if notification.b_read %>
    <tr>
      <% else %>
    <tr class="success">
      <% end %>
      <td><%= notification.content %></td>
      <td><%= notification.created_at.strftime("%B %d, %Y") %></td>

      <td><% if !notification.b_read %><%= link_to user_mark_read_path(current_user), class: 'pull-right btn btn-sm btn-default' do %>
        <%= fa_icon "check" %>  Mark As Read
        <% end %><% end %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= render 'layouts/panel_foot' %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>B read:</strong>
  <%= @notification.b_read %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @notification.imageurl %>
</p>

<p>
  <strong>Notificationurl:</strong>
  <%= @notification.notificationurl %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>