config/routes.rb
Tabby::Application.routes.draw do

  resources :conversations

  resources :blood_pressures

  resources :photos

  resources :galleries

  resources :symptoms
  resources :doctor_visits
  resources :immunizations
  resources :conversations
  resources :messages
  resources :treatments
  resources :pharmacies
  resources :notifications
  resources :droplets
  resources :permissions
  resources :ko_medication_reviews
  resources :appointments
  resources :symptoms
  resources :ko_medications

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end

  get "profiles/show"

  resources :catalogs
  resources :statuses
  resources :documents
  resources :trackers
  resources :pages
  resources :goal_posts
  resources :medications
  resources :handshakes
  resources :conditions do
    resources :posts
    get 'privacy'
    resources :trackers
  end
  resources :episodes do
    resources :posts
  end
  resources :weights
  resources :heights
  resources :allergies
  resources :goal_posts
  resources :pictures
  resources :goals do
    resources :goal_posts
    get 'mark_complete'
  end

  resources :users do
    resources :handshakes
    resources :notifications
    resources :immunizations
    resources :symptoms
    resources :permissions
    resources :doctor_visits
    resources :conversations do
      resources :messages
    end
    resources :trackers do
      resources :datapoints
    end
    get 'mark_read'
    get 'apps'
    get 'network'
    get 'ecard'
    get 'network_feed'
    get 'network_permissions'
    get 'printable'
    get 'dashboard'
    get 'metrics'
    get 'summary'
    resources :pictures
    resources :albums do
      resources :pictures
    end
    resources :allergies
    resources :statuses
    resources :goal_posts
    resources :fitnesses
    resources :goals do
      resources :goal_posts
    end
    resources :conditions
    resources :episodes do
      resources :posts
    end
    resources :heights
    resources :weights
    resources :medications
  end
  resources :albums do
    resources :pictures
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :pictures
  resources :posts
  resources :datapoints

  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get 'static_pages/ecard'
  get 'static_pages/features'
  get "static_pages/company"
  get "static_pages/community_stats"
  get "static_pages/search"
  get "static_pages/roadmap"

  get "albums/form" => 'albums#form', as: :form

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :album
	belongs_to :user
  
  belongs_to :doctor_visit

  has_attached_file :asset, styles: {
    large: "800x800>", medium: "300x200>", small: "260x180>", thumb: "80x80#"
  }

  def to_s
    caption? ? caption : "Picture"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  #before_filter :finds_user
  before_filter :find_album
  #before_filter :find_picture, only: [:edit, :update, :show, :destroy]
  #before_filter :ensure_proper_user, only: [:edit, :new, :create, :update, :destroy]
  #before_filter :add_breadcrumbs


  def destroy
    @picture = Picture.find(params[:id])
    @user = @picture.user
    @picture.destroy
    redirect_to album_pictures_path(@picture.album), :notice => "Successfully destroyed picture."
  end

  def show
    @picture = Picture.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  def index
    @album = Album.find(params[:album_id])
    @pictures = @album.pictures.all
    @user = @album.user
  end

  def new
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.new

  end

  def create
    @picture = @album.pictures.new( picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:user_id, :album_id, :caption, :description, :asset)
  end

  def ensure_proper_user
    if current_user != @user
      flash[:error] = "You don't have permission to do that."
      redirect_to album_pictures_path
    end
  end

  def find_album
    @album = Album.find(params[:album_id])
    #@user = User.find(@album.user_id)
    #@album = @user.albums.find(params[:album_id])
  end

  def find_picture
    @picture = @album.pictures.find(params[:id])
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= simple_form_for([@album, @picture], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :asset, as: :file %>
    <%= f.input :caption, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :description, input_html: { class: 'input-xxlarge', rows: 4 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/sidebar" %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <h2>
            <%= link_to "File Folders", user_albums_path(@user) %> / <strong><%= @album.title %></strong>
            <button class="btn btn-default pull-right" data-toggle="modal" data-target="#myModal">
              <span class="glyphicon glyphicon-picture"></span> Upload File
            </button>
          </h2>
          <hr>

          <!-- Modal -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h3 class="modal-title" id="myModalLabel"> <span class="glyphicon glyphicon-picture"></span> Upload File</h3>
                </div>
                <%= bootstrap_form_for([@album, Picture.new]) do |f| %>
                <div class="modal-body">

                  <%= f.file_field :asset, as: :file %>
                  <%= f.text_field :caption, input_html: { class: 'input-xxlarge' } %>
                  <%= f.hidden_field :description, value: 'blank' %>

                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <%= f.submit "Upload File", class: "btn btn-primary" %>
                </div>
              </div>
              <% end %>
            </div>
          </div>


          <div class="row">
            <% @pictures.each do |picture| %>
            <div class="col-md-3">
              <%= link_to image_tag(picture.asset.url(:small), class: 'img-responsive'), album_picture_path( @album, picture) %>
              <br />
              <div class="caption">
                <% if picture.caption? %><%= picture.caption %><br /><% end %>

                <%= link_to 'View full size', album_picture_path( @album, picture) %>

                <%= link_to "Edit", edit_album_picture_path(@album, picture) %>
                <%= link_to "Delete", album_picture_path(@album, picture), method: :delete, data: { confirm: "Are you sure?" } %>

              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">

<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/show.html.erb
<%= render 'layouts/panel_head' %>
<%= link_to 'Back', album_pictures_path(@picture.album) %>
<center>
  <%= image_tag(@picture.asset.url(:large)) %>
  <p>
    <% if @picture.caption? %>Caption: <%= @picture.caption %><br /><% end %>
    <%= link_to "Edit", edit_picture_path(@picture) %>
    <%= link_to "Delete", picture_path(@picture), method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
</center>
<%= render 'layouts/panel_foot' %>