config/routes.rb
Tabby::Application.routes.draw do

  resources :conversations

  resources :blood_pressures

  resources :photos

  resources :galleries

  resources :symptoms
  resources :doctor_visits
  resources :immunizations
  resources :conversations
  resources :messages
  resources :treatments
  resources :pharmacies
  resources :notifications
  resources :droplets
  resources :permissions
  resources :ko_medication_reviews
  resources :appointments
  resources :symptoms
  resources :ko_medications

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end

  get "profiles/show"

  resources :catalogs
  resources :statuses
  resources :documents
  resources :trackers
  resources :pages
  resources :goal_posts
  resources :medications
  resources :handshakes
  resources :conditions do
    resources :posts
    get 'privacy'
    resources :trackers
  end
  resources :episodes do
    resources :posts
  end
  resources :weights
  resources :heights
  resources :allergies
  resources :goal_posts
  resources :pictures
  resources :goals do
    resources :goal_posts
    get 'mark_complete'
  end

  resources :users do
    resources :handshakes
    resources :notifications
    resources :immunizations
    resources :symptoms
    resources :permissions
    resources :doctor_visits
    resources :conversations do
      resources :messages
    end
    resources :trackers do
      resources :datapoints
    end
    get 'mark_read'
    get 'apps'
    get 'network'
    get 'ecard'
    get 'network_feed'
    get 'network_permissions'
    get 'printable'
    get 'dashboard'
    get 'metrics'
    get 'summary'
    resources :pictures
    resources :albums do
      resources :pictures
    end
    resources :allergies
    resources :statuses
    resources :goal_posts
    resources :fitnesses
    resources :goals do
      resources :goal_posts
    end
    resources :conditions
    resources :episodes do
      resources :posts
    end
    resources :heights
    resources :weights
    resources :medications
  end
  resources :albums do
    resources :pictures
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :pictures
  resources :posts
  resources :datapoints

  root 'static_pages#home'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get 'static_pages/ecard'
  get 'static_pages/features'
  get "static_pages/company"
  get "static_pages/community_stats"
  get "static_pages/search"
  get "static_pages/roadmap"

  get "albums/form" => 'albums#form', as: :form

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  belongs_to :user 
  has_many :photos, :dependent => :destroy
  
  def date
    if self.date_occured != nil
      return date_occured
    else
      return created_at
    end
  end
  
  def self.date_occured
    if self.date_occured == nil
      return self.created_at
    end
  end
  
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @allergies = @user.allergies
  end

  def show
    @allergy = Allergy.find(params[:id])
    @user = @allergy.user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @allergy }
    end
  end

  def update
    @allergy = Allergy.find(params[:id])
    @allergy.update(allergy_params)

    respond_to do |format|
      format.html { redirect_to user_summary_path(current_user), notice: 'Successfully updated!' }
      format.json { head :no_content }
    end
  end

  def new
    @user = User.find(params[:user_id])
    @allergy = @user.allergies.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @allergy }
    end
  end
  
  def edit
    @allergy = Allergy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @allergy }
    end
  end
  
  def destroy
    @allergy = Allergy.find(params[:id])
    @user = @allergy.user
    @allergy.destroy
    redirect_to user_summary_path(@allergy.user), :notice => "Successfully destroyed allergy."
  end

  def create
    @allergy = current_user.allergies.new( allergy_params)

    respond_to do |format|
      if @allergy.save
        format.html { redirect_to user_summary_path(@allergy.user), notice: 'Allergy was successfully created.' }
        format.json { render json: @allergy, status: :created, location: @allergy }
      else
        format.html { render action: "new" }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def allergy_params
    params.require(:allergy).permit(:user_id, :name, :description)
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/views/allergies/_allergies.html.erb
<h2>
  <%= fa_icon "leaf" %> Allergies
  <div class="btn-group pull-right">
    <button class="pull- btn btn-sm btn-default" type="button" data-toggle="collapse" data-target="#collapseForm" aria-expanded="false" aria-controls="collapseExample">
      <%= fa_icon "plus" %> Add
    </button> 
    <%= link_to user_allergies_path(@user), class: 'btn btn-sm  btn-default' do %>
      <%= fa_icon "book" %> History
    <% end %>
  </div>
</h2>
<div class="collapse" id="collapseForm">
  <%= render 'allergies/form' %>
</div>
<% if @user.allergies.none? %>
No allergies listed
<% else %>
<table class='table table-striped table-hover table-responsive'>
  <thead>
    <tr class="info">
      <td>Name</td>
      <td>Notes</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% for allergy in @user.allergies %>
    <tr>
      <td><strong><%= allergy.name %></strong></td>
      <td><%= allergy.description %></td>
      <td>
        <div class="dropdown pull-right">
          <a href="#" class="dropdown-toggle btn btn-default btn-sm pull-right" style="" data-toggle="dropdown">
            <%= fa_icon "gear" %>
          </a>
          <ul class="dropdown-menu pull-right">
            <li>
              <%= link_to edit_allergy_path(allergy) do %>
              <i class='fa fa-gear'></i> Edit
              <% end %>
            </li>
            <li>
              <%= link_to allergy, data: {:confirm => 'Are you sure?'}, 'data-original-title' => "Remove allergy?", :method => :delete do %>
              <i class='fa fa-trash-o'></i> Remove
              <% end %>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/allergies/_allergy.html.erb
<div>
	<p>
		<h4><%= allergy.name %></h4>
		<%= link_to "View", user_allergy_path(@user, allergy) %>
		<%= link_to "Delete", user_allergy_path(@user, allergy), :method => :delete %>
	</p>
</div>

app/views/allergies/_form.html.erb
<%= form_for Allergy.new do |f| %>
<p>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name', class:"form-control" %><br>
  <%= f.text_area :description, placeholder: 'Describe symptoms, severity, or other notes', class:"form-control" %><br>
  
</p>
<%= render 'layouts/form_footer' %>
<% end %>

app/views/allergies/edit.html.erb
<div class="container">
  <%= simple_form_for(@allergy) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/allergies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/sidebar" %>
    </div>
    <div class="col-md-9">
      <%= render 'layouts/panel_head' %>
      <%= render 'allergies/allergies' %>
      <%= render 'layouts/panel_foot' %>
    </div>
  </div>
</div>

app/views/allergies/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1>Add Allergy</h1>
      <%= bootstrap_form_for @allergy do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_field :name %>
      <%= f.text_area :description %>
      <%= render 'layouts/form_footer' %>
      <% end %>
    </div>
  </div>
</div>

app/views/allergies/show.html.erb
<h1>Allergies#show</h1>
<p>Find me in app/views/allergies/show.html.erb</p>